### ISSUE TITLE
Add a description view to app cards

### ISSUE THREAD

**Issue by killthebuddh4** [relaycc/receiver#125]
Context:
* Each app card represents a project
* App cards don't have any information about a project except the name and logo

Feature:
* Add a longish (up to 2 sentences) project description to app cards

Notes/Options:

* The project description probably won't fit into the current default app card view (or maybe it would?):
<img width="284" alt="image" src="https://user-images.githubusercontent.com/100799178/206968757-205521f4-ff85-4f2e-ac6d-7c8f2e5118bc.png">

* In theory we _could_ make the name and logo smaller but that's not the first option we want to try.
* Instead, let's try to include some kind of show/hide functionality.
  * a button that toggles the whole card into a "more info" view or 
  * a hover/long-press state 
  * a button that squishes elements in the current default view and expands some text

**Comment by BrianS111** [comment]
Anything with hover would require a different view for mobile and tablet. If we are okay with having a user clicking buttons on each card to read the description then the same view can work on mobile and desktop

**Comment by BrianS111** [comment]
I think this issue might be in the wrong section. Seems like a Relay not Receiver issue

**Comment by killthebuddh4** [comment]
> I think this issue might be in the wrong section. Seems like a Relay not Receiver issue

You're 100% correct.

**Comment by killthebuddh4** [comment]
Wrong project.
