### ISSUE TITLE
Conversations list header

### ISSUE THREAD

**Issue by killthebuddh4** [relaycc/receiver#28]
* The minimize/close menu should be standardized across all screens
* The "+ new conversation" button is too big to include the minimize and close icons

# Option 1
* Move the "new conversation" button out of the header
* Instead of in the header, the first row of the conversations list could be an input field. The input field could have a "+" button to indicate that it's for creating a conversation. Additionally, when you type in the input, your existing conversation list could be filtered according to your input.

# Option 2

* Instead of the big "new conversation" button
* We use a "+" icon or an "edit" icon
By "edit icon" I mean something like this (screenshot is from iMessage)
<img width="321" alt="image" src="https://user-images.githubusercontent.com/100799178/189576877-371aa3b2-0b04-4930-a195-25b4b0b54243.png">

**Comment by seandaopanel** [comment]
Option 2 looks better imo
