### ISSUE TITLE
Remove styled-components dependency

### ISSUE THREAD

**Issue by killthebuddh4** [relaycc/receiver#30]
* styled components doesn't seem to be a great option for this library
  * styling probably won't be a large part of the dev effort
  * styled-components is pretty opinionated, is a bit touchy about its environment
  * styled-components are a slightly controversial technical choice in general, many people won't like to bundle it
* so we're going to quickly migrate to vanilla CSS
* Will migrate in (at least) 2 phases
  * First we'll just do basically a 1:1 mapping between existing styled-components and classnames in a single `index.css` file
  * After that, we'll organize things as we go, use more traditional CSS patterns, etc

**Comment by ArshErgon** [comment]
I couldn't find any `.css` file, is the style is inside the `.ts` files?

**Comment by killthebuddh4** [comment]
> I couldn't find any `.css` file, is the style is inside the `.ts` files?

Yep, right now we're using [styled-components](https://styled-components.com/). We want to migrate to vanilla css ASAP.

**Comment by killthebuddh4** [comment]
* I think we should use Tailwind because
  * After build time Tailwind is just a stylesheet so shouldn't be too hard to deploy
  * Because it's just a stylesheet, we can ship an unstyled version easily
  * Tailwind supports theming well
  * It's very popular

Need to look into how the CSS reset works, can we scope Tailwind's CSS reset to just our library?

**Comment by killthebuddh4** [comment]
* We need to go through literally component by component and copy-paste the styles for that component into an index.css file with unique classnames for each component
* The classes should be name `.NameOfTsxFile.name-of-styled-component`. For example:
  * .Avatar-button
  * .Window-button
* DO NOT WORRY ABOUT CSS RESET YET

**Comment by killthebuddh4** [comment]
* In terms of an implementation plan, let's do things in this order
* Do a few styled-components that don't take props, check in on how it's going
* Any styled components that do not take props
* A few that do take props
* Check in here
* The rest

**Comment by BrianS111** [comment]
https://github.com/relaycc/receiver/pull/53 Updated PR here. Initial phase of switching is complete except things involving Exports, Props, Animations, Nested Selectors, Svgs. Which will be done in the next round

**Comment by BrianS111** [comment]
https://github.com/relaycc/receiver/pull/53 Updated PR here. All styled components have been removed  and is now ready for this process:

Achilles will do the last few. The build config might have to happen first, I can help with this if necessary.
delete the styled-components dependency!
update the build config (how do we bundle CSS with receiver?)
update the README w/ new instructions on how to include in project
