### ISSUE TITLE
Clear receiver state when wallet changes

### ISSUE THREAD

**Issue by killthebuddh4** [relaycc/receiver#43]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When a new wallet is passed to receiver, receiver state is not updated.

### Expected Behavior

When a new wallet is passed to receiver, receiver state should refresh.

### Steps To Reproduce

* Connect wallet
* Launch receiver
* Connect a new wallet

**Comment by seandaopanel** [comment]
Seems ++EV
