### ISSUE TITLE
Receiver window minimized state

### ISSUE THREAD

**Issue by andrewvdp** [relaycc/receiver#49]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the user minimizes the receiver window, the window appears to be (just barely) visible at the bottom of the page

<img width="523" alt="image" src="https://user-images.githubusercontent.com/5456408/190481455-925e0f0e-4479-4996-8805-faf5af650ac0.png">

### Expected Behavior

After minimizing the receiver window it should not be visible

### Steps To Reproduce

minimize the receiver window in a conversation on react.relay.cc

**Comment by killthebuddh4** [comment]
* If this ticket is going to take more than a couple hours, don't do it. We're going to do a big update to the Window component internals soon anyways.

**Comment by BrianS111** [comment]
https://github.com/relaycc/receiver/pull/57
