### ISSUE TITLE
Ship an unstyled version of receiver

### ISSUE THREAD

**Issue by killthebuddh4** [relaycc/receiver#51]
Depends on #30 

* Right now Receiver styles are not customizable
* Ideally we would provide a tailored/ergonomic customization API
* The previous bullet is a lot of work
* For now we can just ship an unstyled version of Receiver that sites can style themselves
* This option will continue to exist long-term alongside the precision-customization option

**Comment by BrianS111** [comment]
@killthebuddh4 Is this still an issue we want to get done according to the original specs or have things changed since this was opened?

**Comment by killthebuddh4** [comment]
> @killthebuddh4 Is this still an issue we want to get done according to the original specs or have things changed since this was opened?

This is probably not something we need to worry about at the moment and may never have been viable anyways.
