### ISSUE TITLE
Add a CONTRIBUTING.md document

### ISSUE THREAD

**Issue by killthebuddh4** [relaycc/receiver#54]
* Should provide a basic overview of the way development is done in this project.
* Some topics to cover
  * pull requests
  * issues
  * getting help
  * style guides
  * dev enviroment setup

**Comment by seanrelay** [comment]
This will be important in a week or so. GitPOAP is onboarding us to their project, and see we'll have a lot more eyes on the repos that we want. (relay and receiver and ? ).
Basically they'll help us / incentivize opensource contributions.
https://gitpoap.notion.site/GitPOAP-Onboarding-Process-AG-0a99753c401c48b19ab9d77832757270
