### ISSUE TITLE
Mobile views and responsive views

### ISSUE THREAD

**Issue by killthebuddh4** [relaycc/receiver#55]
* We need to support mobile views. This shouldn't be *too* tough but might require a bit of thought/work.
* Additionally, we should make the example sites a little bit responsive.

**Comment by seandaopanel** [comment]
Mobile views P0

**Comment by BrianS111** [comment]
I couldn't agree more

**Comment by killthebuddh4** [comment]
I pushed some changes the make this a lot better but still not good enough. Will continue working on this later today, might be able to get it done. I'm going to try to get some mobile testing options to work better also.

**Comment by killthebuddh4** [comment]
I just realized I'm working off `main` on this. SMH. I'll open a PR.
