### ISSUE TITLE
message address incorrect

### ISSUE THREAD

**Issue by seandaopanel** [relaycc/receiver#59]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="501" alt="Screen Shot 2022-09-19 at 11 01 00 AM" src="https://user-images.githubusercontent.com/102389629/191083611-bda88beb-6c6d-45ef-8d58-0d0ceeff03c4.png">

### Expected Behavior

The person I'm messaging has my own address show up as theirs. 

### Steps To Reproduce

Message someone on demo.relay.cc

**Comment by killthebuddh4** [comment]
To reproduce you have to message someone that doesn't have an ENS name.
