### ISSUE TITLE
Link back to GitHub from the create-react-app demo app

### ISSUE THREAD

**Issue by killthebuddh4** [relaycc/receiver#63]
* In the example react app, put a line at the very top of the page that says
"Relay Receiver is open source, check it out on GitHub".
* The "GitHub" should be the GH logo and it should link to `https://github.com/relaycc/receiver`.
* The style of the line of text should be the same as 
<img width="882" alt="image" src="https://user-images.githubusercontent.com/100799178/192016690-ebb91d63-f579-4b11-b8e3-0ae6fa94a6d3.png">
* The line should be on both the default and dynamic views.

**Comment by BrianS111** [comment]
https://github.com/relaycc/receiver-example-cra/pull/3
