### ISSUE TITLE
Allow for more fonts

### ISSUE THREAD

**Issue by andrewvdp** [relaycc/receiver#65]
There is a need for the user to change the font when they implement receiver. The current request is to allow the ability to use Inter.

**Comment by killthebuddh4** [comment]
* `font-family` is an inherited property, so what we should do for this is to remove all of the `font-family` properties from our CSS. That way the site's font will be applied to Receiver.
* We should add a class to the `Window` component with an easy-to-remember name, like "receiver-window" and then add to the "custom styling" section of the README something that has a tip + example: 
  "To apply custom fonts to Receiver, you can use the "receiver-window" classname"
  ```css
  .receiver-window {
    font-family: 'Your Favorite Font';
  }
  ```

**Comment by BrianS111** [comment]
Are we 100% sure we don't want to have a preselected font in place to start instead of inheriting whatever it's going to inherit from the site? Inheritance is how it looked awful in that one pic Sean posted, and it didn't even seem to match the site much

**Comment by seandaopanel** [comment]
Did profiles support #79 include this?
This is part of Sybil PR path I think.
