### ISSUE TITLE
Unintentional scrolling on conversations list

### ISSUE THREAD

**Issue by BrianS111** [relaycc/receiver#67]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There is unintended horizontal scrolling on the conversations list

### Expected Behavior

The layout should be in a way where there isn't need for horizontal scrolling

### Steps To Reproduce

I will post the video here, but to reproduce.. launch receiver, go to the conversations list view and scroll left/right

https://user-images.githubusercontent.com/81312527/191848051-f86ab9a8-13b8-483b-90b0-d6e7424fa7b5.mov

**Comment by killthebuddh4** [comment]
This is fixed.
