### ISSUE TITLE
Github link on Receiver

### ISSUE THREAD

**Issue by seandaopanel** [relaycc/receiver#70]
In the create message screen, add another text section with a link to https://github.com/relaycc/receiver/

"Receiver is open-source and found at https://github.com/relaycc/receiver/" could be it.

**Comment by killthebuddh4** [comment]
@seandaopanel IMO this should replace the current footer. The logo could stay there, the font made a bit smaller. We could also just add a GitHub logo to the footer. I'm having a hard time picturing an additional text box that doesn't look ramshackle.

**Comment by seandaopanel** [comment]
Sure. The idea is that it's easy for someone to find the github, realize it's simple to install, and put it on their site

**Comment by killthebuddh4** [comment]
Now that I think about that's actually what just the GitHub logo means usually. Like when people put a GH logo on their site it's like "hey check us out on GitHub".

I also think maybe we remove the Relay logo and just have a GH logo.

**Comment by killthebuddh4** [comment]
Ok yeah so @BrianS111 I think what we do is replace the current Receiver footer. Replace it with a line that says
* "Check <Relay Logo> out on <GH Logo>"
* Relay Logo should link to https://try.relay.cc
* GH Logo should link to https://github.com/relaycc/receiver

**Comment by killthebuddh4** [comment]
Closed by #80
