### ISSUE TITLE
XMTP Account not loading 

### ISSUE THREAD

**Issue by seandaopanel** [relaycc/receiver#78]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

My seanwbren.eth account is not message-able after the user signs in to XMTP.

<img width="945" alt="Screen Shot 2022-09-23 at 12 04 20 PM" src="https://user-images.githubusercontent.com/102389629/192039560-717fcbf4-3e8b-45ea-aa5e-f91cf63d66e4.png">
<img width="991" alt="Screen Shot 2022-09-23 at 12 04 27 PM" src="https://user-images.githubusercontent.com/102389629/192039580-944c7a03-902b-45d6-bf75-2f08d31132d1.png">

Seems to be conflating my account with the uniswap.eth account when this non-happy-path initialization flow is used. 

### Expected Behavior

The seanwbren ENS avatar loads, and the XMTP identity loads and I can message. 

### Steps To Reproduce

1. Go to sybil.relay.cc//#/delegates/uniswap/0x0cb27e883E207905AD2A94F9B6eF0C7A99223C37
2. Click bottom right message icon. don't initialize
3. Click Message on my profile to message seanwbren.eth
4. Initialize XMTP

**Comment by seandaopanel** [comment]
Alternate reproduction flow. 
1. Go to sybil.relay.cc//#/delegates/uniswap/0x0cb27e883E207905AD2A94F9B6eF0C7A99223C37
2. Click Message on my profile to message seanwbren.eth
3. Initialize XMTP
4. Observe message is working as intended. 
5. Minimize or click bottom right icon.
6. Uniswap profile loads, and is not on the network.
6. Click to message seanwbren.eth again, and it says "not on xmtp network"

**Comment by seandaopanel** [comment]
#3 alternate flow: 
1. On sybil.relay.cc click bottom right icon.
2. Initialize XMTP and sign.
3. Click to go back to inbox, then new message.
4. Enter vdp.eth or other address. 
5. Conversation loads. 
6. Click "message" button next to a16z

Observe address field changes, but preserves ENS avatar and messages.

**Comment by seandaopanel** [comment]
I think there's some check we can do on the account load step to prevent these issues, marking as P0 for Sybil PR but def timebox if no headway / mysterious cause.

**Comment by seandaopanel** [comment]
@killthebuddh4 all 3 of these are fixed now

**Comment by killthebuddh4** [comment]
Closed by ?? :)
