### ISSUE TITLE
Relay link update

### ISSUE THREAD

**Issue by seandaopanel** [relaycc/receiver#86]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Relay link broken in copy address / relay / etherscan menu

### Expected Behavior

Link to relay.cc/u/[ENS/address]

### Steps To Reproduce

see current behavior.

**Comment by seandaopanel** [comment]
P0 for easy important update.

**Comment by killthebuddh4** [comment]
Fixed by 0b34238d3d4546cb9e5907e1003fdf12a4956ff7
