### ISSUE TITLE
"process is not defined" error when building static site

### ISSUE THREAD

**Issue by nlnw** [relaycc/receiver#87]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If I include relaycc/receiver in a React app built with Vite, the production site does not work and gives this error:

```
Uncaught ReferenceError: process is not defined
    at index.0abb9cfb.js:232:47756
    at index.0abb9cfb.js:241:3373
```

It works if I remove the relay receiver code. This is just vanilla code straight from the examples. It might have something to do with some dependency that's included by relay, but it's hard to isolate the problem.

### Expected Behavior

App does not crash.

### Steps To Reproduce

Create a Vite React app and include relay code, the build the static site. The static site will not work.

**Comment by killthebuddh4** [comment]
@nlnw Thanks for submitting this! I will look into it and report back.

**Comment by nlnw** [comment]
Thanks, was able to repro like this:

- Checkout https://github.com/relaycc/receiver-example-cra/  (optionally update all the dependencies, some are quite old)
- install vite: `npm install vite @vitejs/plugin-react`
- Add simple vite.config.ts:
```
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
});
```
- Add simple index.html:
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title></title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="./src/main.jsx"></script>
  </body>
</html>
```
- Run `npm run build` after setting the script to do `vite build`
- Serve the files output into `dist` (e.g. with `python3 -m http.server`) and notice that the page is blank and console shows "process is not defined".

**Comment by killthebuddh4** [comment]
> Thanks, was able to repro like this:
> 
>     * Checkout https://github.com/relaycc/receiver-example-cra/  (optionally update all the dependencies, some are quite old)
> 
>     * install vite: `npm install vite @vitejs/plugin-react`
> 
>     * Add simple vite.config.ts:
> 
> 
> ```
> import { defineConfig } from "vite";
> import react from "@vitejs/plugin-react";
> 
> export default defineConfig({
>   plugins: [react()],
> });
> ```
> 
>     * Add simple index.html:
> 
> 
> ```
> <!DOCTYPE html>
> <html lang="en">
>   <head>
>     <meta charset="UTF-8" />
>     <meta name="viewport" content="width=device-width, initial-scale=1.0" />
>     <title></title>
>   </head>
>   <body>
>     <div id="root"></div>
>     <script type="module" src="./src/main.jsx"></script>
>   </body>
> </html>
> ```
> 
>     * Run `npm run build` after setting the script to do `vite build`
> 
>     * Serve the files output into `dist` (e.g. with `python3 -m http.server`) and notice that the page is blank and console shows "process is not defined".

I **really** appreciate this comment, will help a ton, thanks! I'll investigate later this evening and let you know what I learn.

**Comment by killthebuddh4** [comment]
@nlnw I was able to install, build, and run a project with Receiver using the Vite + React template from the Vite docs [here](https://vitejs.dev/guide/) (`npm create vite@latest receiver-example-vite -- --template react-ts` is the command I used).

I published [the repo](https://github.com/relaycc/receiver-example-vite). There were 2 issues to work around, both related to newer versions of Vite adhering more closely to standards than some packages expect. Let me know if the repo works for you and/or solves your problem.

For what it's worth, I think attempting to add Vite to an existing `create-react-app` project might create some tough issues to work through because `create-react-app` is built around `webpack` and tries really hard to not expose webpack to the developer.

**Again, thanks a ton for creating this issue! Feedback from developers is super important to us.**

**Comment by nlnw** [comment]
Thank you so much! Well, I only converted the create-react-app as a convenience to repro. For my apps, I'm doing a vite app from scratch without any create-react-app baggage and have the problem, so I think it's a general issue. I don't have this issue for example with the worldcoin widget or rainbowkit, wagmi, etc.

Thanks for the workarounds! Is there some way to remove whatever causes usage of "process.env" and "buffer" as well? The process.env thing seems like some debugging code that probably shouldn't be needed for example.

**Comment by killthebuddh4** [comment]
I didn't save the stack trace, but I believe the `process.env` came from somewhere deep in the dependency tree in a crypto library, so we probably won't be getting rid of that.
 
The `buffer` dependency comes from `@xmtp/xmtp-js` and relates to something that I'd like  see prioritized soonish. It seems like the newest versions of JS build tools are removing support for node polyfills, which means `xmtp-js` isn't compatible with a good fraction of newer projects. I'm probably going to ping their dev team or open an issue about general compatibility in the next week or so.

So I guess the short answer is "maybe", hopefully soonish :) I'm going to mark this issue as closed, please don't hesitate to open issues for anything else you come across! If you're on Discord we have a developers channel [here](https://discord.com/channels/906663102123233311/996933748421570600). Also the [XMTP developers](https://discord.com/channels/831836269558235136/936623389664235590) channel is a good place to get support.
