### ISSUE TITLE
Mobile scrolling when sending a message

### ISSUE THREAD

**Issue by andrewvdp** [relaycc/receiver#91]
After sending a message on receiver, messages do not automatically scroll to the last message.

**Comment by BrianS111** [comment]
Just to make sure we are on the same page.. when I'm at the bottom of a convo, it does show that last message sent after sending. So what we are looking for here is if you're scrolled up maybe halfway through a conversation, and you send a message, you want it to scroll to the bottom? I thought that was functionality we were trying to avoid so sending a message doesn't disrupt reading old messages etc....

**Comment by killthebuddh4** [comment]
It might be that it's working on Android but not on iOS.

Expected:
* If you're scrolled all the way to the bottom of the messages list, and a new message arrives, then you should remain scrolled to the bottom of the messages list

Current on iOS Safari:
* Scroll all the way to the bottom of the messages list
* Send a message
* The new message will show up hidden beneath the input field and the user will have to scroll to see it

**Comment by killthebuddh4** [comment]
@BrianS111 To test on iOS, I'm using [XCode Device Simulator](https://developer.apple.com/library/archive/documentation/IDEs/Conceptual/iOS_Simulator_Guide/GettingStartedwithiOSSimulator/GettingStartedwithiOSSimulator.html). XCode is the official Apple IDE, you can download it on the app store.

**Comment by seandaopanel** [comment]
> if you're scrolled up maybe halfway through a conversation, and you send a message, you want it to scroll to the bottom?

Yes this is normal behavior.

**Comment by killthebuddh4** [comment]
When you send a message it should scroll, but it probably shouldn't scroll when any message comes in.

**Comment by BrianS111** [comment]
> > if you're scrolled up maybe halfway through a conversation, and you send a message, you want it to scroll to the bottom?
> 
> Yes this is normal behavior.

![FEDDC371-8B57-4AD3-860A-B00D6DB34256_4_5005_c](https://user-images.githubusercontent.com/81312527/194671757-5a285b28-926f-4e93-986c-19ee7e0949f9.jpeg)

DIscord only scrolls you back down if you are viewing recent messages, if you are viewing older messages it keeps you where you are. A bit more advanced than doing it one way, but possible

**Comment by killthebuddh4** [comment]
We don't need to worry about that, just use whether or not the user is scrolled at all.

* If the user sends a message, scroll to the bottom
* If the user receives a message, and they are already scrolled all the way down, the message should be visible without additional scrolling
* If the user receives a message, and they aren't already scrolled all the way down, do nothing

**Comment by BrianS111** [comment]
** Current on iOS Safari:

Scroll all the way to the bottom of the messages list
Send a message
The new message will show up hidden beneath the input field and the user will have to scroll to see it ** 

Quoting from above

I can't reproduce this. I used safari on Iphone from the old one we have in the office.. set messages immediately, waited the 5 min it takes to be a new bubble etc. After lunch I'll get on the orig issue of scrolling to the bottom after sending

**Comment by BrianS111** [comment]
The solution I have for the scrolling down when scrolled up thing will probably fix any issues anyone has with scrolling after sending though

**Comment by killthebuddh4** [comment]
@BrianS111 @andrewvdp

* Here's a video of the only bug that needs to be fixed, the other items are less important. That said, if this bug is fixed I think the others should follow pretty easily.

https://user-images.githubusercontent.com/100799178/195193785-ffd6507b-06b2-4c56-904e-598fa8c5afbf.mov
